// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3DCWRPFqJeV3Fu5j20eA2nwO419777UE',
    appId: '1:231820489099:web:c06fdf04cdd1d3bc437f8e',
    messagingSenderId: '231820489099',
    projectId: 'kgjgjg-801a0',
    authDomain: 'kgjgjg-801a0.firebaseapp.com',
    storageBucket: 'kgjgjg-801a0.appspot.com',
    measurementId: 'G-9PQQHYZ3FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx7nBS0eBBYcir3mtubDBqxzw-FfKzcIY',
    appId: '1:231820489099:android:249f00cf5415ccf3437f8e',
    messagingSenderId: '231820489099',
    projectId: 'kgjgjg-801a0',
    storageBucket: 'kgjgjg-801a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwoeW9O3VXGfqLMJi0FBChfhtVnARfd6M',
    appId: '1:231820489099:ios:42049b67300a24e9437f8e',
    messagingSenderId: '231820489099',
    projectId: 'kgjgjg-801a0',
    storageBucket: 'kgjgjg-801a0.appspot.com',
    iosBundleId: 'com.example.totalxtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwoeW9O3VXGfqLMJi0FBChfhtVnARfd6M',
    appId: '1:231820489099:ios:42049b67300a24e9437f8e',
    messagingSenderId: '231820489099',
    projectId: 'kgjgjg-801a0',
    storageBucket: 'kgjgjg-801a0.appspot.com',
    iosBundleId: 'com.example.totalxtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3DCWRPFqJeV3Fu5j20eA2nwO419777UE',
    appId: '1:231820489099:web:ce4907c2d2ccfc82437f8e',
    messagingSenderId: '231820489099',
    projectId: 'kgjgjg-801a0',
    authDomain: 'kgjgjg-801a0.firebaseapp.com',
    storageBucket: 'kgjgjg-801a0.appspot.com',
    measurementId: 'G-8N6NBPVMPQ',
  );
}
